apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - namespace.yaml
  - cron/service-account.yaml
  - cron/restart-gateway-pod.yaml
helmCharts:
  - name: base
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.25.0
    releaseName: istio
    namespace: istio-system
  - name: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.25.0
    releaseName: istiod
    namespace: istio-system
  - name: gateway
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.25.0
    releaseName: istio-ingressgateway
    namespace: istio-system

patches:
  - path: istio-ingress-patch.yaml
    target:
      kind: Service
      name: istio-ingressgateway
      namespace: istio-system