apiVersion: v1
kind: Secret
metadata:
  name: ml-ops-kserve-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/SleepingTalent/ml-ops-kserve-iris.git