---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-deleter
  namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-delete-role
  namespace: istio-system
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-delete-role-binding
  namespace: istio-system
subjects:
  - kind: ServiceAccount
    name: pod-deleter
    namespace: istio-system
roleRef:
  kind: Role
  name: pod-delete-role
  apiGroup: rbac.authorization.k8s.io
