apiVersion: v1
kind: ConfigMap
metadata:
  name: config-autoscaler
  namespace: knative-serving
data:
  # enable scale-to-zero in Knative
  enable-scale-to-zero: "true"
  # allow new Revisions to start at zero
  allow-zero-initial-scale: "true"
