apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    autoscaler:
      enable-scale-to-zero: "true"
      allow-zero-initial-scale: "true"
    domain:
      noveria.ai: ""