apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - knative-serving.yaml
helmCharts:
  - name: knative-operator
    repo: https://knative.github.io/operator
    version: v1.17.4
    releaseName: knative-operator
    namespace: knative-operator

